### ISSUE TITLE
[!] There are multiple dependencies with different sources for RNFtp in Podfile:

### ISSUE THREAD

**Issue by Yali07** [navico-mobile/react-native-ftp-client#12]
I'm trying to install react-native-ftp for my ios app but i'm getting the below error.

here are the steps i follwed,

npm install react-native-ftp --save

react-native link react-native-ftp

cd ios && pod install

[!] There are multiple dependencies with different sources for RNFtp in Podfile:

RNFtp (from ../node_modules/react-native-ftp/ios)
RNFtp (from ../node_modules/react-native-ftp)

**Comment by juanky201271** [comment]
@Yali07 This repo is not react-native-ftp, is another diferent... for your information.
