### ISSUE TITLE
domain = 6, error = 550, errorMessage = Requested action not taken. File unavailable (e.g., file not found, no access).

### ISSUE THREAD

**Issue by ghost** [navico-mobile/react-native-ftp-client#5]
My setup working normally on android but iOS got that error.
`Error: list error unknown_domain(550) Requested action not taken. File unavailable (e.g., file not found, no access).`

xcode log: `domain = 6, error = 550, errorMessage = Requested action not taken. File unavailable (e.g., file not found, no access).`
```javascript
const FTPSetup = (ftpHost) => {
  FtpClient.setup({
    ip_address: "194.5x.xxx.xxx",
    port: 21,
    username: 'uxxxxxx.username.online',
    password: 'xxxxxxxx'
  })
}

export const getListFile = async (ftpHost, remote_file_path = '/public_html') => {
  FTPSetup(ftpHost)
  try {
    return await FtpClient.list(remote_file_path)
  } catch (error) {
    console.log(error)
    Alert.alert('Error', error.message)
    return []
  }
}
```

please help :(

**Comment by juanky201271** [comment]
Hello @ngocthien0507anttech I got the same error, please can you tell me if you had any luck with this? Thanks so much in advance.

**Comment by ghost** [comment]
> Hello @ngocthien0507anttech I got the same error, please can you tell me if you had any luck with this? Thanks so much in advance.

Hi @juanky201271 , the problem came from a different path on iOS and Android. In my case, I check the OS to change the remote_file_path 

something like:
```javascript
let hostPath = Platform.OS === 'android' ? '/public_html/' : '/'
```
if you have more end point behind hostPath, use the processPath fucntion of FtpClient, the full function I used here:
```javascript
const getFiles = async (endPath = null) => {
    setIsLoading(true)
    setup()
    try {
      if (endPath) {
        hostPath = FtpClient.processPath(hostPath, endPath)
      }
      const listOfFiles = await FtpClient.list(hostPath)
      setFileList(listOfFiles)
      setIsLoading(false)
    } catch (error) {
      Alert.alert('ERROR', error.message)
    }
  }
```

**Comment by juanky201271** [comment]
That's is really helpful, I thought the problem was in the local file, but maybe the real problem was the host path. Thanks so much, I really appreciate your help.
